### ISSUE TITLE
compatibility with Arduino framework

### ISSUE THREAD

**Issue by rvxfahim** [feilipu/avrfreertos#16]
This is a question as to how can this library be used to create a minimal example of blink using 1ms tick and a simple blink task for the Arduino framework where setup and loop structure is used. Should I simply include the freertos library in the project ?
The reason I am willing to use this one over the other "Arduino freertos lib" is that I need 1ms time slices.

**Comment by feilipu** [comment]
There would be quite a bit of trimming and rework to make this repository fit the [Arduino_FreeRTOS_Library](https://github.com/feilipu/Arduino_FreeRTOS_Library). This is because this repository has a lot of extra code and libraries that would conflict with things the Arduino platform attempts to do.

> I am willing to use this one over the other "Arduino freertos lib" is that I need 1ms time slices.

I would stick with the Arduino_FreeRTOS_Library, but use the configuration for [Timer 0](https://github.com/feilipu/Arduino_FreeRTOS_Library/blob/master/src/port.c#L50), that will allow you to use 1ms ticks. Timer 0 is an 8 bit timer, so the granularity is not that fine, but it will save the other timers for PWM or other more complex tasks.

Just [change this definition](https://github.com/feilipu/Arduino_FreeRTOS_Library/blob/master/src/FreeRTOSVariant.h#L40) to define `portUSE_TIMER0`, and (it may require some finessing, but) it should just work. You will need to understand how Timer 0 is configured, and your CPU Frequency, to get the desired Tick rate.

You might like to compare the Arduino code with how things are done here too, for reference.

Using Timer 0 will break parts of Arduino platform (namely `millis()` and `micros()`) so you will have to rely on FreeRTOS functions for timing duties.

__EDIT__ Just [checking here](https://github.com/feilipu/avrfreertos/blob/master/freeRTOS10xx/include/FreeRTOSBoardDefs.h#L295), that you'll need to use Timer 1 or Timer 3 to get 1000Hz (1ms) timing. Look at the rest of the file to see how you would convert to use Timer 1.

Using Timer 1 may break many things inside Arduino. I don't have a list at hand, but check in the [Arduino core](https://github.com/arduino/ArduinoCore-avr/tree/master/cores/arduino) to see what is using Timer 1.

**Comment by rvxfahim** [comment]
> **EDIT** Just [checking here](https://github.com/feilipu/avrfreertos/blob/master/freeRTOS10xx/include/FreeRTOSBoardDefs.h#L295), that you'll need to use Timer 1 or Timer 3 to get 1000Hz (1ms) timing. Look at the rest of the file to see how you would convert to use Timer 1.

Thanks for pointing this out, because from the readme of that repo it was written that it uses WDT 15ms by default for all Arduino, or maybe I understood it wrong. So that means for Uno it is already using timer0 as default defined in that file for ticks and I can play with the number to adjust the tick rate?

**Comment by feilipu** [comment]
> > **EDIT** Just [checking here](https://github.com/feilipu/avrfreertos/blob/master/freeRTOS10xx/include/FreeRTOSBoardDefs.h#L295), that you'll need to use Timer 1 or Timer 3 to get 1000Hz (1ms) timing.

> Thanks for pointing this out, because from the readme of that repo it was written that it uses WDT 15ms by default for all Arduino, or maybe I understood it wrong.

For `Arduino_FreeRTOS_Library` the watchdog timer is used by default for all supported hardware, because it is configured identically for all supported hardware. That avoids configuration issues, and avoids conflict with the Arduino platform libraries that configure all other timers for their use.

> So that means for Uno it is already using timer0 as default defined in that file for ticks and I can play with the number to adjust the tick rate?

For this library `avrfreertos` the defaults are based on MCU version, configured from Eclipse IDE settings (which is what I use) and are assumed to be linked to the Arduino products. So for example if the MCU is specified as the ATmega328p, it is assumed to refer to an Arduino [Uno](https://github.com/feilipu/avrfreertos/blob/master/freeRTOS10xx/include/FreeRTOSBoardDefs.h#L265).

IIRC (it has been a while), the Timer 0 can't be configured to timeout fast enough for 1ms intervals. But there might have been some other reason why I've stated that for 1000Hz Ticks, I've noted that Timer 1 (for the ATmega328p) needs to be used.

**Comment by rvxfahim** [comment]
Thanks again, got the two repos mixed up from the hyperlinks. Now everything is clear.
