### ISSUE TITLE
FreeRTOS v10 on 1284P: timer issue

### ISSUE THREAD

**Issue by mrechte** [feilipu/avrfreertos#6]
Hello,
I use your port on a RKAT40 dev (ATmega 1284P) board with AtmelStudio 7.

I am having an issue with software timers. 
When I start a software timer, the callback is never executed and the system becomes erratic (does not crash but it seems RAM is corrupted. Sometimes resets by itself) as soon as as I call xTimerStart().

Have you tested timers on this FreeRTOS version ?
Thanks

**Comment by feilipu** [comment]
Your issue will be most likely caused by stack corruption. The timer task configuration [`configTIMER_TASK_STACK_DEPTH`](https://github.com/feilipu/avrfreertos/blob/master/freeRTOS10xx/include/FreeRTOSConfig.h#L75) takes the [`configMINIMAL_STACK_SIZE`](https://github.com/feilipu/avrfreertos/blob/master/freeRTOS10xx/include/FreeRTOSConfig.h#L52) for its stack configuration by default. This will most likely need to be increased to a larger number than 85 bytes.

You will need to experiment with the best option for you. But, start with 256 bytes to see if that fixes the instability, then work down from there.

**Comment by mrechte** [comment]
Thanks. This is not a stack problem (it was 1000). I suspect some interference with the I2C code generated with Studio Atmel (may not designed to be used with a scheduler). I have to investigate more.

**Comment by feilipu** [comment]
I'm sure you're aware of this, but for completeness and for others finding this thread, FreeRTOS uses a separate stack for each of the defined tasks, the (separate) timer task, and the (separate) idle task. Each one of these stacks needs to be managed.

The idle task is easy. It is usually empty, and needs the minimum stack. Unless you're using my Arduino port where the idle task calls the `loop()` function, where a small initial stack is provided just to get started. However the `loop()` function should ideally also be left empty too.

The timer task may need more or less stack, depending on how the timer callback functions are implemented.  Timer callback functions execute in the context of the timer service task. The stack requirement of the timer service task therefore depends on the stack requirements of the timer callback functions.

Other defined tasks also require their own stacks to be configured correctly. Using the stack high water functions is the best way to inspect and manage these stack sizes.

**Comment by mrechte** [comment]
Thanks for the hints. Actually the problem was stack related: the idle task, despite doing nothing, requires enough stack to service IRQ and the minimum configMINIMAL_STACK_SIZE 85 is not enough in my case.
Can IRQ routines switch to a dedicated stack or does it mean one must provide enough free space for IRQ processing in all task's stacks ?
I use the ASF generated I2C files, which are not aware of freeRTOS, they may not be optimal for such case.
I noticed that your repository includes i2c code, who is maintaining that portion ?

**Comment by feilipu** [comment]
> Actually the problem was stack related: the idle task, despite doing nothing, requires enough stack to service IRQ.
> Can IRQ routines switch to a dedicated stack or does it mean one must provide enough free space for IRQ processing in all task's stacks ?

As an interrupt can occur at any time, unless you dedicate a separate stack location to service the interrupt, and manage the stack pointer on entry and exit, then every task needs to keep enough free stack to handle any / all interrupts.

If your interrupt is too large (needing a lot of stack or other handling) it is much better to take it out of the interrupt (when the scheduler will be disabled because your interrupt routine will normally be running with disabled interrupts) and just use a mutex semaphore to block a task dedicated to processing the interrupt code which can be simply "given" by the interrupt and then exit.

The AVR ATmega is relatively bad at this because it only has one global interrupt level, compared to modern 32bit devices.

> I noticed that your [repository includes i2c code](https://github.com/feilipu/avrfreertos/blob/master/freeRTOS10xx/lib_io/i2cMultiMaster.c), who is maintaining that portion ?

It is me. That code is developed by integrating example code from AVR and has been tested on [a few example programs](https://github.com/feilipu/avrfreertos/tree/master/PeggyVideoPong) for my purposes. But, I'd not be 100% certain that it is correct in all corner cases, and the multi-master handling code has never been tested. But, certainly for day to day usage the I2C Master or Slave modes work well.
